### ISSUE TITLE
SVG Path not rendered correctly

### ISSUE THREAD

**Issue by ananthachetan** [I2Djs/I2Djs#13]
Sometimes the d attribute of SVG <path> is not parsed correctly leading to unexpected path outputs.

The path tag generated in codepen output:
`<path d="M11.6 269s-19.7-42.4 6.06-68.2 48.5-6.06 59.1 12.1l-3.03 28.8 209-227s45.5-21.2 60.6 1.52c15.2 22.7-3.03 47-3.03 47l-225 229s33.1-12 48.5 7.58c50 63.6-50 97-62.1 37.9" stroke-width="5px" fill="none" stroke="black"></path>`

The path tag generated from i2djs code:
`<path d="M 11.6,269 C 11.6,269 -8.1,226.6 17.660000000000004,200.8 C 17.66,200.8 66.16,194.74 76.76,212.9 L 73.73,241.70000000000002 L 282.73,14.700000000000017 C 282.73,14.700000000000017 328.23,-6.499999999999982 343.33000000000004,16.220000000000013 C 358.53000000000003,38.920000000000016 340.30000000000007,63.22000000000001 340.30000000000007,63.22000000000001 L 115.30000000000007,292.22 C -109.69999999999993,521.22 148.4000000000001,280.22 163.80000000000007,299.79999999999995 C 213.80000000000007,363.40000000000003 113.80000000000007,396.8 101.70000000000007,337.7 " stroke-miterlimit="0" style="stroke-width: 5px; stroke: rgb(240, 0, 0); fill: none;"></path>`

**Comment by nswamy14** [comment]
Fixed.
