### ISSUE TITLE
Demos have problems

### ISSUE THREAD

**Issue by Zireael07** [I2Djs/I2Djs#97]
**Describe the bug**
1) Network demo click doesn't work
2) Solar system demo is 404

**To Reproduce**
Click demo links in readme, play around

**Expected behavior**
Demos work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Vivaldi
 - Version 6.8

**Comment by nswamy14** [comment]
Thanks for reporting this. The Solar System demo example has been removed, and I will update the list accordingly. 
The Network example appears to be working fine: https://i2djs.github.io/I2Djs/examples/canvas/networkSystem.html

**Comment by Zireael07** [comment]
Clicks do nothing, and I now noticed that every one spams this in the console:
Uncaught TypeError: Cannot read properties of undefined (reading 'dx')
    at nt.<anonymous> (networkSystem.html:42:55)
    at r.onDrag (i2d.esm.min.js:6:70841)
    at $n.execute (i2d.esm.min.js:6:71448)
    at Hr.pointermoveCheck (i2d.esm.min.js:6:36469)
    at HTMLCanvasElement.<anonymous> (i2d.esm.min.js:6:861637)

**Comment by mohitkumartoshniwal** [comment]
The link is working fine for me

**Comment by nswamy14** [comment]
Closing this as it is not a bug. Appears to some network issue in downloading the data.

**Comment by Zireael07** [comment]
Not a network issue - I just rechecked after Ctrl+F5 and it still persists.
